INCLUDE_CJSON=1
include ../common/config.mk

TARGET = kidui

LDFLAGS := $(LDFLAGS) -lSDL -lSDL_ttf -lSDL_image -lSDL_rotozoom -lm -pthread -lkbinput

include ../common/commands.mk
include ../common/recipes.mk
